### ISSUE TITLE
Update ipywidget to version 8

### ISSUE THREAD

**Issue by DonJayamanne** [github/codespaces-jupyter#500]
Hi, I’m one of the engineers working on the Jupyter extension
The Jupyter extension supports ipywidgets

thought I’d mention that in case the right was that 8 was still not supported by vscode Jupyter

**Comment by prateek121212** [comment]
so i have an issue regarding the jupyter book. kindly ping on my mail to discuss further.

**Comment by Ahmedidoumou** [comment]
I don’t understand ?
Thank you

Le lun. 29 janv. 2024 à 11:54, prateek121212 ***@***.***> a
écrit :

**Comment by prateek121212** [comment]
kindly ping me on my mail.
prateeksuper94@gmail.com.
plz also attach the configured file

**Comment by TIJBRAND1996** [comment]
Brandon311097@gmail.com
