### ISSUE TITLE
Ok> Following [this guide](https://docs.github.com/en/codespaces/developing-in-a-codespace/getting-started-with-github-codespaces-for-machine-learning#configuring-nvidia-cuda-for-your-codespace), use CUDA to enable GPU access. This would be helpful for many AI workflows.

### ISSUE THREAD

**Issue by Abhi7739309** [github/codespaces-jupyter#568]
> Following [this guide](https://docs.github.com/en/codespaces/developing-in-a-codespace/getting-started-with-github-codespaces-for-machine-learning#configuring-nvidia-cuda-for-your-codespace), use CUDA to enable GPU access. This would be helpful for many AI workflows.

Ok

_Originally posted by @Abhi7739309 in https://github.com/github/codespaces-jupyter/issues/542#issuecomment-2260590442_

**Comment by Luisvelix** [comment]
gh repo clone github/codespaces-jupyter
